description: The RIOXX metadata application profile has been developed for repositories to share metadata about the scholarly resources they contain.
identifiers:
- id: msc:m1004
  scheme: RDA-MSCWG
locations:
- type: namespace
  url: http://www.rioxx.net/schema/v2.0/rioxx/
- type: website
  url: https://www.rioxx.net/
- type: namespace
  url: https://www.rioxx.net/schema/v2.0/rioxxterms/
- type: namespace
  url: http://docs.rioxx.net/schema/v1.0/

title: RIOXX Metadata Application Profile
keywords:
- Multidisciplinary
acronym: rioxx